### ISSUE TITLE
CSS - Mobile check sizes and font weight is 400 not 500

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#588]
Present:

![Image](https://user-images.githubusercontent.com/37311649/187764307-e6eb8613-c2f3-4182-9165-51178306e6db.png)

FIGMA:

![Image](https://user-images.githubusercontent.com/37311649/187764390-172bdbfe-5882-4b6a-a288-9d23a57f28f4.png)

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`

**Comment by jonsnowpt** [comment]
@migbash 

Still incorrect:

- [ ] Space between the date and teams (left and right)
- [ ] Media icon size
- [ ] Space between icons
- [ ] Less round corners in the betting sites icons

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`
