### ISSUE TITLE
SEO - Missing links

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#599]
Missing the following SEO:

- [ ] fixtures link
- [ ] tip links

**Comment by migbash** [comment]
@jonsnowpt links are there on `SEO` no ?

![Image](https://user-images.githubusercontent.com/20924663/188282583-651445db-9c71-4dc5-b513-8b3ff1c655e4.png)

Or they need to be as `detectable` links `[hyperlinks]` ?

**Comment by jonsnowpt** [comment]
@migbash 

We need them as links, you can remove them as text.

**Comment by migbash** [comment]
`Fixed` reflected in the next `Pull-request` on `DEV`

**Comment by jonsnowpt** [comment]
@migbash 

You can remove the team, names, fixtures links, media links, and tip links from the text content.



![Image](https://user-images.githubusercontent.com/37311649/188283060-8a4a62c1-7e68-416a-ab94-2db24bf0b47c.png)

**Comment by jonsnowpt** [comment]
Hi @migbash 

Still showing them:



![Image](https://user-images.githubusercontent.com/37311649/188570036-193751e5-23b4-430c-90b5-d807dd3302dd.png)

**Comment by jonsnowpt** [comment]
@migbash 

I will restructure how it should be shown and add it to a future sprint.
