### ISSUE TITLE
Undefined replaced by "-"

### ISSUE THREAD

**Issue by jonsnowpt** [Betarena/scores#609]
When we get an undefined value, replace it by "-"

**Comment by jonsnowpt** [comment]
@migbash 

https://scores.betarena.com/br/futebol/estonia/ii-liiga

**Comment by migbash** [comment]
`Fixed` and available in the next `pull-request` deployment

![Image](https://user-images.githubusercontent.com/20924663/189978105-cf3a9d96-a83e-470a-9cdb-c6b3522e0637.png)

**Comment by jonsnowpt** [comment]
@migbash 

Still having issues if selecting the previous year:



![Image](https://user-images.githubusercontent.com/37311649/189987627-e8275e85-a72b-47b8-bb16-2f814a39a27c.png)

**Comment by migbash** [comment]
`Fixed` and updated in the next `pull-request` deployment
